---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${TEST_DISTRO:-centos:7}
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  flake8
